name: Build
on:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: andreibegu/tarkov-item-bot
    steps:

      - name: Login to Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t ${IMAGE_TAG}:${GITHUB_REF#refs/tags/v} .

      - name: Publish image
        run: docker push ${IMAGE_TAG}

      - name: Logout
        run: docker logout 
